"""Generate web-sized copies of the gallery photos.

The originals in images/<category>/ are full-resolution phone photos (2-5 MB
each), which are far too heavy to serve directly. This script writes:

  images/web/thumb/<category>/<file>  - ~800px, used for the grid tiles
  images/web/large/<category>/<file>  - ~2000px, used in the lightbox viewer

Run it after adding photos (and add the file names to images/images-list.js):

  pip install pillow
  python tools/build-images.py

Existing outputs are skipped unless the original is newer.
"""
import json
from pathlib import Path

from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parent.parent
IMAGES = ROOT / "images"
OUT = IMAGES / "web"
SIZES = {"thumb": (800, 72), "large": (2000, 82)}
EXTS = {".jpg", ".jpeg", ".png", ".webp"}


def main():
    for cat in sorted(p for p in IMAGES.iterdir() if p.is_dir() and p.name != "web"):
        for src in sorted(cat.iterdir()):
            if src.suffix.lower() not in EXTS:
                continue
            for kind, (edge, quality) in SIZES.items():
                dest = OUT / kind / cat.name / (src.stem + ".jpg")
                if dest.exists() and dest.stat().st_mtime >= src.stat().st_mtime:
                    continue
                dest.parent.mkdir(parents=True, exist_ok=True)
                with Image.open(src) as im:
                    im = ImageOps.exif_transpose(im).convert("RGB")
                    im.thumbnail((edge, edge), Image.LANCZOS)
                    im.save(dest, "JPEG", quality=quality, optimize=True, progressive=True)
                print(f"{kind}: {cat.name}/{dest.name}")

    # Record thumbnail dimensions so the gallery grid can reserve space before load.
    sizes = {}
    for thumb in sorted((OUT / "thumb").glob("*/*.jpg")):
        with Image.open(thumb) as im:
            sizes[f"{thumb.parent.name}/{thumb.name}"] = list(im.size)
    with open(OUT / "sizes.js", "w", newline="\n") as f:
        f.write("// Generated by tools/build-images.py - do not edit.\n")
        f.write("const galleryImageSizes = {\n")
        for key, size in sizes.items():
            f.write(f"  {json.dumps(key)}: {json.dumps(size)},\n")
        f.write("};\n")


if __name__ == "__main__":
    main()
